FROM bitnami/spark:latest
USER root

# copy and install Python deps
COPY streaming_requirements.txt /app/
RUN pip3 install --upgrade pip \
 && pip3 install -r /app/streaming_requirements.txt

COPY pyspark_streaming.py /app/
WORKDIR /app

ENTRYPOINT ["python3", "pyspark_streaming.py"]