AWSTemplateFormatVersion: "2010-09-09"
Description: "Secrets Manager Template for Reddit Credentials"

Parameters:
  RedditClientId:
    Type: String
    Description: "The Reddit Client ID"

  RedditClientSecret:
    Type: String
    Description: "The Reddit Client Secret"

  RedditUserAgent:
    Type: String
    Description: "The Reddit User Agent"

Resources:
  RedditClientIdSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: redditstream-REDDIT_CLIENT_ID
      Description: "Reddit Client ID"
      SecretString: !Ref RedditClientId

  RedditClientSecretSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: redditstream-REDDIT_CLIENT_SECRET
      Description: "Reddit Client Secret"
      SecretString: !Ref RedditClientSecret

  RedditUserAgentSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: redditstream-REDDIT_USER_AGENT
      Description: "Reddit User Agent"
      SecretString: !Ref RedditUserAgent

Outputs:
  RedditClientIdOutput:
    Description: "The name of the Secrets Manager secret for Reddit Client ID"
    Value: redditstream-REDDIT_CLIENT_ID

  RedditClientSecretOutput:
    Description: "The name of the Secrets Manager secret for Reddit Client Secret"
    Value: redditstream-REDDIT_CLIENT_SECRET

  RedditUserAgentOutput:
    Description: "The name of the Secrets Manager secret for Reddit User Agent"
    Value: redditstream-REDDIT_USER_AGENT
