AWSTemplateFormatVersion: "2010-09-09"
Description: "Secrets Manager Template for Reddit Credentials"

Parameters:
  RedditClientId:
    Type: String
    Description: "The Reddit Client ID"

  RedditClientSecret:
    Type: String
    Description: "The Reddit Client Secret"

  RedditUserAgent:
    Type: String
    Description: "The Reddit User Agent"

  BucketName:
    Type: String
    Description: "The globally unique name for your S3 bucket"

Resources:
  RedditClientIdSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: redditstream-REDDIT_CLIENT_ID
      Description: "Reddit Client ID"
      SecretString: !Ref RedditClientId

  RedditClientSecretSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: redditstream-REDDIT_CLIENT_SECRET
      Description: "Reddit Client Secret"
      SecretString: !Ref RedditClientSecret

  RedditUserAgentSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: redditstream-REDDIT_USER_AGENT
      Description: "Reddit User Agent"
      SecretString: !Ref RedditUserAgent
    

  StreamingBucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: redditstream-BUCKET_NAME
      Description: "S3 bucket name for Reddit streaming data"
      Type: String
      Value: !Ref BucketName

Outputs:
  RedditClientIdOutput:
    Description: "The name of the Secrets Manager secret for Reddit Client ID"
    Value: redditstream-REDDIT_CLIENT_ID

  RedditClientSecretOutput:
    Description: "The name of the Secrets Manager secret for Reddit Client Secret"
    Value: redditstream-REDDIT_CLIENT_SECRET

  RedditUserAgentOutput:
    Description: "The name of the Secrets Manager secret for Reddit User Agent"
    Value: redditstream-REDDIT_USER_AGENT

  StreamingBucketNameOutput:
    Description: "SSM Parameter path for the S3 bucket name"
    Value: redditstream-BUCKET_NAME