name: Deploy SSM Parameters Stack

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation Stack for SSM Parameters
        run: |
          aws cloudformation deploy \
            --stack-name reddit-ssm-stack \
            --template-file SSM.yaml \
            --parameter-overrides \
                RedditClientId=${{ secrets.REDDIT_CLIENT_ID }} \
                RedditClientSecret=${{ secrets.REDDIT_CLIENT_SECRET }} \
                RedditUserAgent=${{ secrets.REDDIT_USER_AGENT }} \
            --capabilities CAPABILITY_NAMED_IAM
